//! Cell-bucketed broad phase: the spatial index and its query surface.
//!
//! [`SpatialGrid`] buckets colliders into fixed-size cells and yields the
//! set of possibly-overlapping index pairs. [`ColliderId`] is the durable
//! handle for a collider that must survive a removal, and [`AoiScratch`]
//! is the reusable buffer for the per-client area-of-interest query.
//!
//! Everything the grid returns is a *candidate*: a bounding square is not
//! a shape. Callers run the [`narrow`](super::narrow) probes over the
//! results.

use glam::DVec2;
use std::collections::{HashMap, HashSet};

/// Cell-bucketed broad-phase.
///
/// Colliders are inserted with `(index, pos, radius)` — the grid puts
/// each collider into every cell its bounding square overlaps, so a
/// pair query only needs to read a single cell rather than a 3×3
/// neighbourhood. `query_pairs` returns unique index pairs (`a < b`).
pub struct SpatialGrid {
    cell_size: f64,
    /// Keyed by `(partition, cx, cy)`. The partition is an opaque
    /// caller-supplied tag (0 when unused) that hard-separates
    /// colliders which share coordinates but must never interact.
    ///
    /// Without it, a caller whose world stacks independent groups at
    /// the same coordinates gets every cross-group pair generated by
    /// the broad phase and then has to reject them one at a time —
    /// which is O(N^2) in the number of co-located groups no matter
    /// how cheap the rejection is. Partitioning keeps them out of the
    /// same bucket in the first place.
    cells:     HashMap<(u32, i32, i32), Vec<u32>>,
    /// Retained per-collider bounds so `query_pairs` doesn't need the
    /// caller to hand them back — one insert, one query.
    ///
    /// Indexed by *slot*, not by live-collider ordinal: [`remove`] leaves
    /// a hole rather than compacting, so entries here may be dead. Read
    /// through `alive` before trusting one.
    ///
    /// [`remove`]: Self::remove
    bounds:    Vec<(DVec2, f64)>,
    /// Partition tag per slot, parallel to `bounds`.
    parts:     Vec<u32>,
    /// Whether each slot currently holds a collider. Parallel to `bounds`.
    ///
    /// Holes exist because compacting on remove would renumber a *live*
    /// collider, and callers hold indices within a tick — AoI hands
    /// `scratch.hits` to a relevancy mapping, pair lists name two indices.
    /// Silently moving one is the "told about the wrong entity" failure
    /// this whole generational scheme exists to make impossible.
    alive:     Vec<bool>,
    /// Reuse counter per slot, bumped on every [`remove`]. A
    /// [`ColliderId`] only resolves while its generation matches, so an
    /// id held across a remove fails closed instead of silently naming
    /// whatever took the slot.
    ///
    /// [`remove`]: Self::remove
    gens:      Vec<u32>,
    /// Slots freed by [`remove`], ready for the next insert.
    ///
    /// [`remove`]: Self::remove
    free:      Vec<u32>,
    /// Live collider count, tracked rather than derived: `bounds.len()`
    /// is the slot count once holes exist.
    live:      usize,
}

/// A stable handle to one collider in a [`SpatialGrid`].
///
/// The bare `u32` index that [`SpatialGrid::insert`] returns is a *slot*,
/// and [`SpatialGrid::remove`] frees slots for reuse. An index alone
/// therefore cannot distinguish "the collider I inserted" from "whatever
/// was put in its place afterwards" — the same problem [`EntityId`] solves
/// for the ECS, solved the same way.
///
/// Indices remain the currency *within* a tick: [`query_pairs`] and
/// [`AoiScratch::hits`] both yield raw indices, because nothing is removed
/// mid-query and resolving a generation per hit would cost more than it
/// buys. Hold a `ColliderId` when a handle must survive a
/// [`SpatialGrid::remove`]; hold an index when it must not.
///
/// [`EntityId`]: crate::ecs::EntityId
/// [`query_pairs`]: SpatialGrid::query_pairs
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub struct ColliderId {
    pub index: u32,
    pub generation: u32,
}

impl SpatialGrid {
    /// Build an empty grid with the given cell size (world units).
    ///
    /// # Sizing it
    ///
    /// Aim for a **mean bucket occupancy in the low single digits**, and
    /// measure it for your own world rather than copying a number. That
    /// is the quantity [`query_pairs`](Self::query_pairs) actually tracks:
    /// its cost grows with the sum of the squares of bucket sizes, so a
    /// cell that buckets tens of colliders is quadratically worse than one
    /// that buckets a few.
    ///
    /// Occupancy is the target rather than a cell-to-collider ratio,
    /// because no single ratio holds. Measured at 20k colliders, the best
    /// cell was 32x the collider diameter at radius 1, 8x at radius 5, and
    /// 2x at radius 25 — the ratio moves with density, while the occupancy
    /// at the optimum stays small in every case.
    ///
    /// Distribution matters more than count. The same 40k colliders of
    /// radius 2, total time for one rebuild plus one `query_pairs`:
    ///
    /// | world              | best cell | total   | mean bucket there |
    /// | ------------------ | --------- | ------- | ----------------- |
    /// | uniform over 10 km |      32 m |  6.8 ms |               1.2 |
    /// | clustered, 2 km    |      32 m |  7.9 ms |               1.4 |
    /// | clustered, 500 m   |      16 m | 10.5 ms |               1.7 |
    /// | clustered, 150 m   |       8 m | 23.7 ms |               2.9 |
    /// | clustered, 50 m    |       4 m |  119 ms |               5.8 |
    ///
    /// Two things to take from the last row. Tight clustering pulls the
    /// best cell *down*, so a size tuned on a uniform world is badly wrong
    /// for a crowded one — at 400 m that same clustered world costs over
    /// three seconds. And at genuinely dense clustering **no cell size
    /// fits a 33.3 ms tick**: tuning has run out, and the fix is fewer
    /// pairs (partitions, smaller worlds, a different broad phase), not a
    /// better number here.
    ///
    /// Ship-sized colliders top out around 50 m; 400 m is the shipping
    /// default in void_sim and holds up for that workload — a few thousand
    /// ships spread over kilometres keeps buckets nearly empty, and 400 m
    /// measures within noise of the best cell there. It is the wrong
    /// default for small, numerous, clustered colliders.
    pub fn new(cell_size: f64) -> Self {
        Self {
            cell_size,
            cells: HashMap::new(),
            bounds: Vec::new(),
            parts: Vec::new(),
            alive: Vec::new(),
            gens: Vec::new(),
            free: Vec::new(),
            live: 0,
        }
    }

    /// Drop every collider, keeping the allocated capacity.
    ///
    /// This is what a caller rebuilding the grid each tick should use
    /// instead of assigning a fresh [`new`](Self::new): the `HashMap` and
    /// the parallel vectors keep their buffers, so a steady-state rebuild
    /// stops allocating entirely. Bucket `Vec`s are retained too — the
    /// map keeps its keys and each bucket is emptied in place, because a
    /// world's occupied cells are nearly the same set tick to tick.
    ///
    /// Slot numbering restarts from zero, which is what makes this safe
    /// for the index-per-tick callers: after `clear`, the next insert is
    /// slot 0 again, exactly as a fresh grid would assign. Any
    /// [`ColliderId`] from before the clear is stale and will not resolve,
    /// because generations are preserved across it.
    ///
    /// # Cost
    ///
    /// Measured against `SpatialGrid::new` on the same workload, rebuild
    /// alone (insert only, no query):
    ///
    /// | world                  | fresh    | cleared  |
    /// | ---------------------- | -------- | -------- |
    /// | 10k lattice, cell 40   |  0.84 ms |  0.32 ms |
    /// | 50k lattice, cell 40   |  4.09 ms |  1.72 ms |
    /// | 100k sparse, cell 400  |  3.41 ms |  2.07 ms |
    /// | 100k sparse, cell 40   | 10.95 ms |  3.00 ms |
    ///
    /// The gain grows with the number of *cells*, not colliders: many
    /// small buckets is where per-tick allocation dominates, so the
    /// 40-unit cell gains 3.6x where the 400-unit one gains 1.6x. Pair
    /// sets were verified identical between the two arms at every size.
    pub fn clear(&mut self) {
        for bucket in self.cells.values_mut() {
            bucket.clear();
        }
        self.bounds.clear();
        self.parts.clear();
        self.alive.clear();
        // Generations are deliberately *not* cleared: a `ColliderId` handed
        // out before this clear must not resolve against a slot that a
        // later insert reuses. Keeping the counters means slot 0's next
        // occupant has a different generation than slot 0's last one.
        for g in self.gens.iter_mut() {
            *g += 1;
        }
        self.free.clear();
        self.live = 0;
    }

    /// Insert a collider with its centre + bounding radius. Returns
    /// the index the pair query will yield.
    ///
    /// Equivalent to `insert_partitioned(pos, rad, 0)` — use that when
    /// the world stacks independent groups at shared coordinates.
    pub fn insert(&mut self, pos: DVec2, rad: f64) -> u32 {
        self.insert_partitioned(pos, rad, 0)
    }

    /// Insert into a specific partition. Colliders in different
    /// partitions never share a cell and therefore never appear as a
    /// pair, however close together they are.
    pub fn insert_partitioned(&mut self, pos: DVec2, rad: f64, partition: u32) -> u32 {
        let idx = if let Some(slot) = self.free.pop() {
            let i = slot as usize;
            self.bounds[i] = (pos, rad);
            self.parts[i] = partition;
            self.alive[i] = true;
            slot
        } else {
            let slot = self.bounds.len() as u32;
            self.bounds.push((pos, rad));
            self.parts.push(partition);
            self.alive.push(true);
            self.gens.push(0);
            slot
        };
        self.live += 1;
        self.hook(idx, pos, rad, partition);
        idx
    }

    /// Insert and return a handle that survives later removals.
    ///
    /// Same cost as [`insert_partitioned`](Self::insert_partitioned) —
    /// the generation is already tracked either way. Use this when the
    /// handle outlives the tick; use the plain insert when the index is
    /// consumed before anything can be removed.
    pub fn insert_tracked(&mut self, pos: DVec2, rad: f64, partition: u32) -> ColliderId {
        let index = self.insert_partitioned(pos, rad, partition);
        ColliderId { index, generation: self.gens[index as usize] }
    }

    /// Remove a collider, freeing its slot for reuse.
    ///
    /// Returns whether the slot held a live collider. The slot's
    /// generation is bumped, so any [`ColliderId`] naming it stops
    /// resolving — a later insert may take the slot, and must not
    /// inherit the old id.
    ///
    /// Indices already handed out this tick (in a pair list, in
    /// [`AoiScratch::hits`]) are *not* invalidated by this in any way the
    /// type system sees: they are bare `u32`s and will happily index the
    /// slot's new occupant. Finish consuming a query's output before
    /// removing anything it named.
    pub fn remove(&mut self, index: u32) -> bool {
        let i = index as usize;
        if !self.alive.get(i).copied().unwrap_or(false) {
            return false;
        }
        let (pos, rad) = self.bounds[i];
        let partition = self.parts[i];
        self.unhook(index, pos, rad, partition);
        self.alive[i] = false;
        self.gens[i] += 1;
        self.free.push(index);
        self.live -= 1;
        true
    }

    /// Move or resize a live collider in place.
    ///
    /// Returns false if the slot is a hole. Cheap when the collider stays
    /// within the cells it already occupies — the common case for a body
    /// drifting a fraction of a cell per tick — because the bucket
    /// membership is then unchanged and only the retained bounds move.
    pub fn update(&mut self, index: u32, pos: DVec2, rad: f64) -> bool {
        let i = index as usize;
        if !self.alive.get(i).copied().unwrap_or(false) {
            return false;
        }
        let (old_pos, old_rad) = self.bounds[i];
        let partition = self.parts[i];
        let old_span = self.span(old_pos, old_rad);
        let new_span = self.span(pos, rad);
        if old_span != new_span {
            self.unhook(index, old_pos, old_rad, partition);
            self.hook(index, pos, rad, partition);
        }
        self.bounds[i] = (pos, rad);
        true
    }

    /// The inclusive cell range a bounding square covers.
    #[inline]
    fn span(&self, pos: DVec2, rad: f64) -> ((i32, i32), (i32, i32)) {
        (self.cell(pos - DVec2::splat(rad)), self.cell(pos + DVec2::splat(rad)))
    }

    /// Add `idx` to every cell its bounding square overlaps.
    fn hook(&mut self, idx: u32, pos: DVec2, rad: f64, partition: u32) {
        let ((cx0, cy0), (cx1, cy1)) = self.span(pos, rad);
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                self.cells.entry((partition, cx, cy)).or_default().push(idx);
            }
        }
    }

    /// Remove `idx` from every cell its bounding square overlaps.
    ///
    /// `swap_remove` on the bucket: bucket order is not meaningful —
    /// `query_pairs` sorts its output and the dedupe is order-independent
    /// — so there is no reason to pay for a shift.
    fn unhook(&mut self, idx: u32, pos: DVec2, rad: f64, partition: u32) {
        let ((cx0, cy0), (cx1, cy1)) = self.span(pos, rad);
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                let Some(bucket) = self.cells.get_mut(&(partition, cx, cy)) else { continue };
                if let Some(at) = bucket.iter().position(|&b| b == idx) {
                    bucket.swap_remove(at);
                }
            }
        }
    }

    /// Number of live colliders.
    ///
    /// Not the same as the index space once [`remove`](Self::remove) has
    /// left holes — see [`slot_count`](Self::slot_count).
    pub fn len(&self) -> usize { self.live }
    pub fn is_empty(&self) -> bool { self.live == 0 }

    /// Size of the index space: one past the highest slot ever used.
    ///
    /// This, not [`len`](Self::len), is what sizes anything indexed by
    /// collider slot — [`AoiScratch`] stamps, a caller's own parallel
    /// array. With holes present it is larger than the live count.
    pub fn slot_count(&self) -> usize { self.bounds.len() }

    /// How many cells currently hold at least one collider.
    ///
    /// Paired with [`len`](Self::len) this gives mean bucket occupancy,
    /// which [`new`](Self::new) documents at length as *the* quantity to
    /// tune cell size against — its cost grows with the sum of the squares
    /// of bucket sizes, and a badly-chosen cell measured 64x worse than a
    /// good one on the same world.
    ///
    /// Those docs tell a caller to "measure it for your own world rather
    /// than copying a number", and until 2026-09-11 gave them no way to:
    /// `cells` is private and nothing reported its size. A tuning target
    /// nobody can observe is advice, not guidance.
    ///
    /// ```
    /// # use void_engine::collision::SpatialGrid;
    /// # use glam::DVec2;
    /// let mut g = SpatialGrid::new(10.0);
    /// for i in 0..100 {
    ///     g.insert(DVec2::new(i as f64 * 5.0, 0.0), 1.0);
    /// }
    /// let occupancy = g.len() as f64 / g.occupied_cells().max(1) as f64;
    /// assert!(occupancy > 0.0);
    /// ```
    ///
    /// Counts cells across every partition: two partitions occupying the
    /// same coordinates are two entries, because they are two buckets and
    /// each is scanned separately.
    ///
    /// Note this counts cells that are *allocated*, which after
    /// [`clear`](Self::clear) includes emptied buckets retained for reuse
    /// — so read it after filling the grid, not before.
    pub fn occupied_cells(&self) -> usize {
        self.cells.values().filter(|b| !b.is_empty()).count()
    }

    /// Whether a slot currently holds a collider.
    pub fn slot_alive(&self, index: u32) -> bool {
        self.alive.get(index as usize).copied().unwrap_or(false)
    }

    /// Resolve a durable handle to its slot index, or `None` if the
    /// collider it named has since been removed.
    ///
    /// This is the check that makes slot reuse safe: a stale id fails here
    /// rather than silently naming whatever now occupies the slot.
    pub fn resolve(&self, id: ColliderId) -> Option<u32> {
        let i = id.index as usize;
        if self.alive.get(i).copied().unwrap_or(false)
            && self.gens.get(i).copied() == Some(id.generation)
        {
            Some(id.index)
        } else {
            None
        }
    }

    /// The durable handle for a live slot, or `None` if it is a hole.
    pub fn id_of(&self, index: u32) -> Option<ColliderId> {
        if self.slot_alive(index) {
            Some(ColliderId { index, generation: self.gens[index as usize] })
        } else {
            None
        }
    }

    /// Enumerate every unique index pair (`a < b`) whose bounding
    /// squares overlap. Deduplicated via a packed-u64 hash set so
    /// multi-cell colliders don't yield the same pair twice.
    ///
    /// Sharing a cell is the coarse test; overlapping is the one that is
    /// returned. Two colliders at opposite corners of the same cell
    /// share it without being anywhere near each other, and on a
    /// mixed-radius world three quarters of same-cell pairs are like
    /// that — so they are rejected here rather than handed to a caller
    /// who would reject them anyway.
    ///
    /// **Pair order is deterministic**: the result is sorted ascending by
    /// `(a, b)`. It did not used to be — pairs came out in `HashMap`
    /// bucket order, and `RandomState` is seeded per process, so the same
    /// world produced a different pair order on every run. Any caller
    /// whose resolution is order-sensitive (impulses applied in sequence,
    /// first-hit-wins damage) therefore produced a different simulation
    /// from identical inputs, which silently breaks replay, lockstep and
    /// server/client agreement. Sorting costs one O(n log n) pass over
    /// the pair list and buys back reproducibility.
    ///
    /// # Cost
    ///
    /// Every collider still *visits* every other collider sharing a cell,
    /// so the scan is proportional to the sum of the squares of bucket
    /// sizes and the constant is set entirely by cell size — see
    /// [`new`](Self::new) for how to pick one, because the difference
    /// between a good and a bad choice measured 64x on the same world.
    /// What the overlap test changes is what survives that scan, and the
    /// saving tracks how much of the world is merely co-located rather
    /// than touching. On 100k mixed-radius colliders spread over
    /// kilometres it halves the total — 67.6 ms to 33.0 ms, 42.3 to 20.1
    /// — and on the regular lattice `benches/hot_paths.rs` builds it is
    /// 2.9x, 5.07 ms to 1.76 ms, where all 55,552 pairs it used to return
    /// were colliders sharing a cell whose squares never touched.
    ///
    /// The rejected pairs never reach the hash set or the sort, which is
    /// where the cost sat: hashing 649k pairs measured 21.9 ms against
    /// 0.4 ms to sort them.
    ///
    /// There is a density past which no cell size and no rejection help.
    /// 100k colliders packed into 150-metre knots still costs ~180 ms,
    /// and the shape of that is worth recognising before reaching for a
    /// faster broad phase: the narrow phase over those pairs costs
    /// 1.45 ms, and each collider overlaps 9.6 others. A body resolving
    /// ten simultaneous penetrations every tick has a problem this layer
    /// cannot fix. Worlds at 1.3 and 0.3 overlaps per collider measure
    /// 33 ms and 21 ms for the same entity count.
    ///
    /// The returned pairs are **broad-phase candidates** in the sense
    /// that a bounding square is not a shape: two overlapping squares
    /// may hold a circle and an oriented box that miss each other.
    /// Callers still run their own narrow phase
    /// ([`circle_vs_circle`](super::circle_vs_circle),
    /// [`obb_vs_obb`](super::obb_vs_obb),
    /// [`circle_vs_obb`](super::circle_vs_obb)) over the list — there is
    /// just far less list to run it over.
    pub fn query_pairs(&self) -> Vec<(u32, u32)> {
        let mut checked: HashSet<u64> = HashSet::new();
        let pack = |a: u32, b: u32| -> u64 { ((a as u64) << 32) | b as u64 };
        let mut pairs: Vec<(u32, u32)> = Vec::new();
        for (i, &(pos, rad)) in self.bounds.iter().enumerate() {
            // Holes left by `remove` keep their slot in `bounds`, so the
            // scan has to skip them — their stale position would otherwise
            // generate pairs against a collider that is no longer here.
            if !self.alive[i] { continue }
            let part = self.parts[i];
            let (cx0, cy0) = self.cell(pos - DVec2::splat(rad));
            let (cx1, cy1) = self.cell(pos + DVec2::splat(rad));
            for cy in cy0..=cy1 {
                for cx in cx0..=cx1 {
                    let Some(bucket) = self.cells.get(&(part, cx, cy)) else { continue };
                    for &j in bucket {
                        if i as u32 == j { continue; }
                        // Reject before the dedupe set ever sees the pair.
                        // Sharing a cell is not the same as being near:
                        // measured on a mixed-radius world, three quarters
                        // of same-cell pairs have bounding squares that do
                        // not touch at all. Four comparisons here remove
                        // them from the hashing, the vector and the sort
                        // together, which is where the cost actually was —
                        // hashing 649k pairs measured 21.9 ms against
                        // 0.4 ms to sort them.
                        let (other, orad) = self.bounds[j as usize];
                        let reach = rad + orad;
                        if (pos.x - other.x).abs() > reach || (pos.y - other.y).abs() > reach {
                            continue;
                        }
                        let (a, b) = if (i as u32) < j { (i as u32, j) } else { (j, i as u32) };
                        if checked.insert(pack(a, b)) { pairs.push((a, b)); }
                    }
                }
            }
        }
        // See the doc comment: the traversal above reads `HashMap` buckets,
        // so insertion order into `pairs` is process-seed dependent.
        pairs.sort_unstable();
        pairs
    }

    /// Enumerate indices whose bounding-square shares any cell the
    /// segment `a → b` passes through. Each index is yielded at most
    /// once. Cell traversal is a grid-DDA (Amanatides-Woo style) so a
    /// long segment only touches the cells it actually crosses, not the
    /// AABB of its endpoints — the latter degrades to O(dx·dy) for
    /// diagonal shots. Callers still need to run their own narrow-phase
    /// (e.g. `swept_hit`) against the returned candidates.
    ///
    /// The `+1` cell of pad on each side of the traversal mirrors the
    /// hand-rolled projectile grid the sim used to carry: it catches
    /// colliders straddling a cell boundary that the segment doesn't
    /// technically enter, but whose bounding square does.
    pub fn query_segment(&self, a: DVec2, b: DVec2) -> Vec<u32> {
        self.query_segment_in(a, b, 0)
    }

    /// `query_segment` restricted to one partition.
    pub fn query_segment_in(&self, a: DVec2, b: DVec2, partition: u32) -> Vec<u32> {
        let mut seen: HashSet<u32> = HashSet::new();
        let mut out:  Vec<u32>     = Vec::new();
        let visit_cell = |cx: i32, cy: i32,
                          seen: &mut HashSet<u32>,
                          out:  &mut Vec<u32>| {
            for pad_y in -1..=1 {
                for pad_x in -1..=1 {
                    let Some(bucket) = self.cells.get(&(partition, cx + pad_x, cy + pad_y))
                    else { continue };
                    for &idx in bucket {
                        if seen.insert(idx) { out.push(idx); }
                    }
                }
            }
        };

        // Grid-DDA from `a` to `b`. Fast-path a stationary segment.
        let (ax, ay) = self.cell(a);
        let (bx, by) = self.cell(b);
        if ax == bx && ay == by {
            visit_cell(ax, ay, &mut seen, &mut out);
            return out;
        }

        let dir = b - a;
        // Steps of ±1 in whichever axes actually change.
        let step_x = if dir.x > 0.0 { 1 } else if dir.x < 0.0 { -1 } else { 0 };
        let step_y = if dir.y > 0.0 { 1 } else if dir.y < 0.0 { -1 } else { 0 };
        // Parametric `t` at which the ray crosses the next cell boundary
        // in each axis. `t_delta` is how much `t` advances per full cell.
        let next_bound = |v: f64, step: i32| -> f64 {
            let cell_f = (v / self.cell_size).floor();
            if step > 0 { (cell_f + 1.0) * self.cell_size }
            else if step < 0 { cell_f * self.cell_size }
            else { f64::INFINITY }
        };
        let mut t_max_x = if step_x != 0 { (next_bound(a.x, step_x) - a.x) / dir.x } else { f64::INFINITY };
        let mut t_max_y = if step_y != 0 { (next_bound(a.y, step_y) - a.y) / dir.y } else { f64::INFINITY };
        let t_delta_x = if step_x != 0 { (self.cell_size / dir.x).abs() } else { f64::INFINITY };
        let t_delta_y = if step_y != 0 { (self.cell_size / dir.y).abs() } else { f64::INFINITY };

        let (mut cx, mut cy) = (ax, ay);
        visit_cell(cx, cy, &mut seen, &mut out);
        // Cap the step count as a safety net — a well-formed segment
        // needs at most |dx| + |dy| + 1 cells. `+ 4` to absorb the pad.
        let max_steps = (bx - ax).unsigned_abs() as usize
                      + (by - ay).unsigned_abs() as usize + 4;
        for _ in 0..max_steps {
            if cx == bx && cy == by { break; }
            if t_max_x < t_max_y {
                cx += step_x;
                t_max_x += t_delta_x;
            } else {
                cy += step_y;
                t_max_y += t_delta_y;
            }
            visit_cell(cx, cy, &mut seen, &mut out);
        }
        out
    }

    /// Enumerate indices whose bounding-square shares any cell the disc
    /// `center` / `radius` overlaps. Each index is yielded at most once.
    ///
    /// **Broad-phase only**, matching [`query_segment`](Self::query_segment):
    /// the result is every candidate in the cells covering the disc's AABB,
    /// not a distance-filtered set. Corner cells reach `radius * √2` past
    /// the centre and a cell holds anything anywhere inside it, so callers
    /// that need a true radius must run their own
    /// `(pos - center).length_squared() <= radius * radius` narrow-phase.
    /// Handing back the raw cell contents keeps the one caller that wants
    /// a cheap "roughly nearby" window from paying for a filter it would
    /// only redo with its own metric.
    pub fn query_circle(&self, center: DVec2, radius: f64) -> Vec<u32> {
        self.query_circle_in(center, radius, 0)
    }

    /// `query_circle` restricted to one partition.
    pub fn query_circle_in(&self, center: DVec2, radius: f64, partition: u32) -> Vec<u32> {
        let mut seen: HashSet<u32> = HashSet::new();
        let mut out:  Vec<u32>     = Vec::new();
        let (cx0, cy0) = self.cell(center - DVec2::splat(radius));
        let (cx1, cy1) = self.cell(center + DVec2::splat(radius));
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                let Some(bucket) = self.cells.get(&(partition, cx, cy)) else { continue };
                for &idx in bucket {
                    if seen.insert(idx) { out.push(idx); }
                }
            }
        }
        out
    }

    /// True-radius query into a caller-owned scratch buffer: the
    /// interest-management primitive.
    ///
    /// Differs from [`query_circle`](Self::query_circle) in what it costs
    /// and what it returns, which is why it exists separately rather than
    /// replacing it. That one is a broad phase — it hands back raw cell
    /// contents and allocates a fresh `HashSet` + `Vec` per call, the
    /// right trade for a caller making a handful of queries with its own
    /// metric. Area-of-interest makes one query *per connected client per
    /// tick*, and at that rate the allocation and the hashing dominate.
    ///
    /// Measured at 100k colliders uniformly scattered over a 10 km square,
    /// 1000 clients, 500-unit radius on a 400-unit grid: 42.7 ms through
    /// `query_circle` against a 33.3 ms budget at 30 Hz, versus
    /// 12.4–13.3 ms here — ~3.2x, and the difference between not fitting
    /// in the tick and leaving ~20 ms for whatever the caller does with
    /// the result. Cost tracks bucket occupancy, so a denser or more
    /// uniform layout measures lower: the `benches/hot_paths.rs` guard
    /// builds a regular lattice and sees ~7.3 ms on the same counts.
    ///
    /// Results land in `scratch.hits`. Colliders are included when their
    /// *centre* lies within `radius` — a true disc, not the AABB of the
    /// cells covering it, so the caller does not redo the filter. That
    /// also makes the result smaller: 755k hits versus the broad phase's
    /// 1.83M on the same workload.
    ///
    /// Sorted ascending, which costs ~0.2 ms per 1000 queries. Bucket
    /// traversal is already deterministic — a checksum over unsorted
    /// output is identical across processes, so unlike `query_pairs` this
    /// does not need a sort to escape `RandomState` seeding. It is here so
    /// a caller diffing against last tick's set can do so with a merge
    /// rather than a set, which is worth 0.2 ms.
    pub fn query_circle_into(
        &self,
        center: DVec2,
        radius: f64,
        partition: u32,
        scratch: &mut AoiScratch,
    ) {
        // Sized by the index space, not the live count: `first_visit`
        // stamps by slot, and holes keep their slots.
        scratch.begin(self.slot_count());
        let r2 = radius * radius;
        let (cx0, cy0) = self.cell(center - DVec2::splat(radius));
        let (cx1, cy1) = self.cell(center + DVec2::splat(radius));
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                let Some(bucket) = self.cells.get(&(partition, cx, cy)) else { continue };
                for &idx in bucket {
                    // A collider spanning several cells appears in each of
                    // them, so the visit still has to be deduplicated —
                    // measured at 44% of colliders with a 50 m radius on a
                    // 400 m grid. The stamp does it without hashing.
                    if !scratch.first_visit(idx) { continue }
                    if self.bounds[idx as usize].0.distance_squared(center) <= r2 {
                        scratch.hits.push(idx);
                    }
                }
            }
        }
        scratch.hits.sort_unstable();
    }

    #[inline]
    fn cell(&self, pos: DVec2) -> (i32, i32) {
        ((pos.x / self.cell_size).floor() as i32,
         (pos.y / self.cell_size).floor() as i32)
    }
}

/// Reusable buffers for [`SpatialGrid::query_circle_into`].
///
/// Hold one per query loop and reuse it across every client in the tick —
/// constructing one per query would reintroduce exactly the allocation the
/// method exists to avoid.
///
/// Deduplication is a generation-stamped vector rather than a `HashSet`:
/// `stamp[idx] == generation` answers "seen this query?" in one indexed
/// compare with no hashing, and bumping `generation` clears the whole set
/// in O(1) between queries.
#[derive(Default)]
pub struct AoiScratch {
    /// Indices within the queried radius, ascending. Valid until the next
    /// query through this scratch.
    pub hits:   Vec<u32>,
    /// Per-collider "last query that visited this index", parallel to the
    /// grid's `bounds`.
    stamp:      Vec<u32>,
    /// Bumped per query. Wrapping is handled by a full reset at the
    /// sentinel, so a 32-bit counter cannot alias a stale stamp.
    generation: u32,
}

impl AoiScratch {
    pub fn new() -> Self { Self::default() }

    /// Ready the buffers for one query over `len` colliders.
    ///
    /// `pub(super)` rather than private so `grid3d` can drive the same
    /// scratch: the dedupe machinery is dimension-free, and duplicating it
    /// would mean two copies of the generation-stamp logic to keep in step.
    pub(super) fn begin(&mut self, len: usize) {
        self.hits.clear();
        // `u32::MAX` is the "never visited" sentinel, so a fresh or
        // grown region must start there rather than at 0 — which is a
        // legitimate generation.
        if self.stamp.len() < len {
            self.stamp.resize(len, u32::MAX);
        }
        // One generation short of the sentinel, wipe and restart. Without
        // this the counter would eventually reach `u32::MAX` and every
        // untouched slot would read as already-visited, silently emptying
        // every subsequent query.
        if self.generation == u32::MAX - 1 {
            self.stamp.fill(u32::MAX);
            self.generation = 0;
        } else {
            self.generation += 1;
        }
    }

    /// Claim `idx` for this query, returning false if already claimed.
    ///
    /// `pub(super)` for the same reason as [`Self::begin`].
    #[inline]
    pub(super) fn first_visit(&mut self, idx: u32) -> bool {
        let slot = &mut self.stamp[idx as usize];
        if *slot == self.generation { return false }
        *slot = self.generation;
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grid_yields_overlap_pair() {
        let mut g = SpatialGrid::new(10.0);
        g.insert(DVec2::new(0.0, 0.0), 2.0);
        g.insert(DVec2::new(1.0, 0.0), 2.0);
        g.insert(DVec2::new(1000.0, 0.0), 2.0);
        let pairs = g.query_pairs();
        assert!(pairs.contains(&(0, 1)));
        assert!(!pairs.iter().any(|&(a, b)| a == 2 || b == 2));
    }

    #[test]
    fn grid_pair_dedup() {
        // Two large colliders that straddle the same 4 cells; the pair
        // must appear exactly once in the query result.
        let mut g = SpatialGrid::new(10.0);
        g.insert(DVec2::new(0.0, 0.0), 15.0);
        g.insert(DVec2::new(5.0, 5.0), 15.0);
        let pairs = g.query_pairs();
        let count = pairs.iter().filter(|&&p| p == (0, 1)).count();
        assert_eq!(count, 1, "{pairs:?}");
    }

    #[test]
    fn circle_query_covers_cells_and_excludes_far_ones() {
        let mut g = SpatialGrid::new(100.0);
        let near = g.insert(DVec2::new(10.0, 10.0), 0.0);
        let adj  = g.insert(DVec2::new(150.0, 10.0), 0.0);   // next cell over
        let far  = g.insert(DVec2::new(9_000.0, 0.0), 0.0);  // way outside

        let hits = g.query_circle(DVec2::new(0.0, 0.0), 100.0);
        assert!(hits.contains(&near));
        assert!(hits.contains(&adj), "adjacent cell is inside the AABB");
        assert!(!hits.contains(&far));

        // Radius == cell size always yields the 3×3 window, whatever the
        // alignment of the query point within its cell.
        for px in [0.0, 50.0, 99.9, 100.0] {
            let mut probe = SpatialGrid::new(100.0);
            for cy in -2..=2 {
                for cx in -2..=2 {
                    probe.insert(DVec2::new(cx as f64 * 100.0 + 50.0,
                                            cy as f64 * 100.0 + 50.0), 0.0);
                }
            }
            let n = probe.query_circle(DVec2::new(px, 50.0), 100.0).len();
            assert_eq!(n, 9, "px = {px} should hit a 3x3 window");
        }
    }

    /// The distinction from `query_circle`: this one filters to the true
    /// disc. A collider sitting in a corner cell of the AABB but outside
    /// the radius is exactly the case the broad phase yields and this
    /// must not.
    #[test]
    fn aoi_query_excludes_what_the_broad_phase_would_yield() {
        let mut g = SpatialGrid::new(100.0);
        let inside = g.insert(DVec2::new(50.0, 0.0), 0.0);
        // (90, 90) is |p| ≈ 127 — inside the 100-unit AABB's corner cell,
        // outside the 100-unit disc.
        let corner = g.insert(DVec2::new(90.0, 90.0), 0.0);

        let broad = g.query_circle(DVec2::ZERO, 100.0);
        assert!(broad.contains(&corner), "the broad phase yields the corner; that is its contract");

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 100.0, 0, &mut scratch);
        assert!(scratch.hits.contains(&inside));
        assert!(!scratch.hits.contains(&corner), "a true-radius query must drop the corner");
    }

    /// A collider spanning several cells is in each of their buckets, so
    /// the stamp has to deduplicate it. Without that it would be reported
    /// once per cell it touches.
    #[test]
    fn aoi_query_yields_a_multi_cell_collider_once() {
        let mut g = SpatialGrid::new(10.0);
        // Radius 35 over a 10-unit grid spans a 7×7 block of cells.
        let big = g.insert(DVec2::ZERO, 35.0);

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 50.0, 0, &mut scratch);
        assert_eq!(scratch.hits.iter().filter(|&&i| i == big).count(), 1,
                   "a collider in 49 buckets must still be reported once");
    }

    /// Reuse is the whole point of the scratch, so a second query must not
    /// inherit the first's results.
    #[test]
    fn aoi_scratch_reuse_does_not_leak_between_queries() {
        let mut g = SpatialGrid::new(100.0);
        let left  = g.insert(DVec2::new(-1_000.0, 0.0), 0.0);
        let right = g.insert(DVec2::new( 1_000.0, 0.0), 0.0);

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::new(-1_000.0, 0.0), 50.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![left]);

        g.query_circle_into(DVec2::new(1_000.0, 0.0), 50.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![right], "the previous query's hit must be gone");

        // And a query matching nothing empties it rather than leaving stale
        // contents behind.
        g.query_circle_into(DVec2::new(0.0, 50_000.0), 10.0, 0, &mut scratch);
        assert!(scratch.hits.is_empty());
    }

    /// The generation counter wraps. At the sentinel the stamp array must
    /// be wiped, or every untouched slot reads as already-visited and all
    /// subsequent queries silently come back empty.
    #[test]
    fn aoi_scratch_survives_generation_wraparound() {
        let mut g = SpatialGrid::new(100.0);
        let only = g.insert(DVec2::ZERO, 0.0);

        let mut scratch = AoiScratch::new();
        // Drive the counter to one below the sentinel, where `begin` resets.
        g.query_circle_into(DVec2::ZERO, 50.0, 0, &mut scratch);
        scratch.generation = u32::MAX - 2;

        for _ in 0..3 {
            g.query_circle_into(DVec2::ZERO, 50.0, 0, &mut scratch);
            assert_eq!(scratch.hits, vec![only], "a wrap must not empty the query");
        }
        assert!(scratch.generation < 4, "the counter must have reset, not saturated");
    }

    /// A scratch reused against a grid that has grown since must cover the
    /// new colliders rather than indexing a short stamp array.
    #[test]
    fn aoi_scratch_grows_with_the_grid() {
        let mut g = SpatialGrid::new(100.0);
        g.insert(DVec2::ZERO, 0.0);

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 50.0, 0, &mut scratch);
        assert_eq!(scratch.hits.len(), 1);

        for _ in 0..64 { g.insert(DVec2::ZERO, 0.0); }
        g.query_circle_into(DVec2::ZERO, 50.0, 0, &mut scratch);
        assert_eq!(scratch.hits.len(), 65, "colliders added after the scratch was sized");
        assert!(scratch.hits.windows(2).all(|w| w[0] < w[1]), "ascending and deduplicated");
    }

    /// Partitions hard-separate colliders, and the AoI path must honour
    /// that the same way the broad phase does.
    #[test]
    fn aoi_query_respects_partitions() {
        let mut g = SpatialGrid::new(100.0);
        let mine = g.insert_partitioned(DVec2::ZERO, 0.0, 3);
        let _theirs = g.insert_partitioned(DVec2::ZERO, 0.0, 4);

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 50.0, 3, &mut scratch);
        assert_eq!(scratch.hits, vec![mine], "another partition must be invisible");
    }

    #[test]
    fn segment_query_hits_traversed_cells() {
        // Grid-DDA against a diagonal shot: the segment must yield both
        // colliders on its path but skip a far-off one.
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(5.0, 5.0),   1.0);   // start cell
        let b = g.insert(DVec2::new(35.0, 35.0), 1.0);   // end cell
        let c = g.insert(DVec2::new(15.0, 15.0), 1.0);   // en-route
        let d = g.insert(DVec2::new(500.0, 0.0), 1.0);   // far away
        let hits = g.query_segment(DVec2::new(0.0, 0.0), DVec2::new(40.0, 40.0));
        assert!(hits.contains(&a));
        assert!(hits.contains(&b));
        assert!(hits.contains(&c));
        assert!(!hits.contains(&d));
    }

    #[test]
    fn segment_query_stationary_returns_local_bucket() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(5.0, 5.0), 1.0);
        let far = g.insert(DVec2::new(100.0, 100.0), 1.0);
        let hits = g.query_segment(DVec2::new(5.0, 5.0), DVec2::new(5.0, 5.0));
        assert!(hits.contains(&a));
        assert!(!hits.contains(&far));
    }

    #[test]
    fn segment_query_dedups() {
        // Wide collider spanning several cells must appear once.
        let mut g = SpatialGrid::new(10.0);
        let big = g.insert(DVec2::new(20.0, 20.0), 15.0);
        let hits = g.query_segment(DVec2::new(0.0, 0.0), DVec2::new(40.0, 40.0));
        assert_eq!(hits.iter().filter(|&&i| i == big).count(), 1);
    }
}

#[cfg(test)]
mod partition_tests {
    use super::*;

    /// Colliders in different partitions never pair, however close.
    #[test]
    fn different_partitions_never_pair() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert_partitioned(DVec2::ZERO, 50.0, 1);
        let b = g.insert_partitioned(DVec2::ZERO, 50.0, 2);
        let pairs = g.query_pairs();
        assert!(!pairs.contains(&(a.min(b), a.max(b))),
            "colliders in different partitions must not pair");
        assert!(pairs.is_empty());
    }

    #[test]
    fn same_partition_still_pairs() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert_partitioned(DVec2::ZERO, 50.0, 7);
        let b = g.insert_partitioned(DVec2::new(10.0, 0.0), 50.0, 7);
        assert_eq!(g.query_pairs(), vec![(a.min(b), a.max(b))]);
    }

    /// The un-partitioned API is partition 0, so existing callers are
    /// unaffected.
    #[test]
    fn plain_insert_behaves_as_partition_zero() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert(DVec2::ZERO, 50.0);
        let b = g.insert_partitioned(DVec2::new(10.0, 0.0), 50.0, 0);
        assert_eq!(g.query_pairs(), vec![(a.min(b), a.max(b))]);
    }

    /// **The scaling property this exists for.** N groups stacked at one
    /// coordinate must stay linear, not quadratic. Un-partitioned, N
    /// co-located colliders generate N*(N-1)/2 pairs; partitioned, zero.
    #[test]
    fn stacked_groups_do_not_explode_the_pair_count() {
        const GROUPS: u32 = 200;
        let mut partitioned = SpatialGrid::new(400.0);
        let mut flat        = SpatialGrid::new(400.0);
        for g in 0..GROUPS {
            partitioned.insert_partitioned(DVec2::ZERO, 50.0, g);
            flat.insert(DVec2::ZERO, 50.0);
        }
        assert_eq!(partitioned.query_pairs().len(), 0,
            "distinct partitions must yield no cross pairs");
        assert_eq!(flat.query_pairs().len() as u32, GROUPS * (GROUPS - 1) / 2,
            "sanity: un-partitioned really is quadratic here");
    }

    #[test]
    fn circle_and_segment_queries_respect_partitions() {
        let mut g = SpatialGrid::new(400.0);
        let mine   = g.insert_partitioned(DVec2::ZERO, 50.0, 3);
        let _other = g.insert_partitioned(DVec2::ZERO, 50.0, 4);

        assert_eq!(g.query_circle_in(DVec2::ZERO, 100.0, 3), vec![mine]);
        assert_eq!(g.query_segment_in(DVec2::new(-500.0, 0.0), DVec2::new(500.0, 0.0), 3),
                   vec![mine]);
    }

    /// `query_pairs` must return the same order every time. It used to
    /// inherit `HashMap` bucket order, which `RandomState` seeds per
    /// process — so this assertion failed across runs, not within one.
    /// Building several grids in one process and comparing is the part
    /// that is testable here; the sort is what makes it hold across
    /// processes too.
    #[test]
    fn query_pairs_order_is_deterministic() {
        let build = || {
            let mut g = SpatialGrid::new(10.0);
            // Enough overlapping colliders to span many cells and buckets.
            for i in 0..64u32 {
                let f = i as f64;
                g.insert(DVec2::new(f * 3.0, (f * 7.0) % 40.0), 6.0);
            }
            g.query_pairs()
        };
        let first = build();
        assert!(first.len() > 32, "expected a substantial pair list, got {}", first.len());
        for _ in 0..8 {
            assert_eq!(build(), first, "pair order varied between identical grids");
        }
        // And it is genuinely sorted, not merely stable by luck.
        let mut sorted = first.clone();
        sorted.sort_unstable();
        assert_eq!(first, sorted, "pairs are not in ascending (a, b) order");
    }

}

/// Incremental update: `remove`, `update`, `clear`, and the generational
/// handles that make slot reuse safe.
#[cfg(test)]
mod incremental_tests {
    use super::*;

    /// The whole reason `ColliderId` exists. A slot freed by `remove` is
    /// reused by the next insert, and the previous handle must not resolve
    /// to the new occupant — that is the "client told about the wrong
    /// entity" failure, and it is silent without the generation.
    #[test]
    fn a_reused_slot_does_not_answer_to_the_old_id() {
        let mut g = SpatialGrid::new(10.0);
        let first = g.insert_tracked(DVec2::new(1.0, 1.0), 1.0, 0);
        assert_eq!(g.resolve(first), Some(first.index));

        assert!(g.remove(first.index));
        assert_eq!(g.resolve(first), None, "a removed collider must stop resolving");

        let second = g.insert_tracked(DVec2::new(50.0, 50.0), 1.0, 0);
        assert_eq!(second.index, first.index, "the freed slot should be reused");
        assert_ne!(second.generation, first.generation, "reuse must bump the generation");
        assert_eq!(g.resolve(first), None, "the stale id must not name the new occupant");
        assert_eq!(g.resolve(second), Some(second.index));
    }

    /// A hole keeps its slot in `bounds`, so the pair scan has to skip it
    /// rather than generate pairs against a stale position.
    #[test]
    fn query_pairs_ignores_removed_colliders() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(0.0, 0.0), 2.0);
        let b = g.insert(DVec2::new(1.0, 0.0), 2.0);
        assert_eq!(g.query_pairs(), vec![(a.min(b), a.max(b))]);

        assert!(g.remove(b));
        assert!(g.query_pairs().is_empty(), "a removed collider must not pair");

        // And the survivor is still findable by a query that reads buckets.
        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 5.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![a], "the live collider must survive its neighbour's removal");
    }

    /// `unhook` has to clear the slot from *every* cell its square covered,
    /// not just the one holding its centre — otherwise a removed collider
    /// keeps appearing in queries against its outlying cells.
    #[test]
    fn removing_a_multi_cell_collider_clears_every_bucket() {
        let mut g = SpatialGrid::new(10.0);
        // Radius 15 on a 10-unit grid spans a 4x4 block of cells.
        let big = g.insert(DVec2::new(0.0, 0.0), 15.0);
        let mut scratch = AoiScratch::new();

        // Present in an outlying cell before removal.
        g.query_circle_into(DVec2::new(12.0, 12.0), 20.0, 0, &mut scratch);
        assert!(scratch.hits.contains(&big));

        assert!(g.remove(big));
        for probe in [DVec2::new(12.0, 12.0), DVec2::new(-12.0, 12.0), DVec2::ZERO] {
            g.query_circle_into(probe, 20.0, 0, &mut scratch);
            assert!(scratch.hits.is_empty(), "a stale bucket entry survived at {probe:?}");
        }
    }

    /// Moving a collider across a cell boundary must change its bucket
    /// membership; moving it within one cell must not need to.
    #[test]
    fn update_moves_bucket_membership() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(1.0, 1.0), 1.0);
        let mut scratch = AoiScratch::new();

        // Far away: not found.
        g.query_circle_into(DVec2::new(100.0, 100.0), 5.0, 0, &mut scratch);
        assert!(scratch.hits.is_empty());

        assert!(g.update(a, DVec2::new(100.0, 100.0), 1.0));
        g.query_circle_into(DVec2::new(100.0, 100.0), 5.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![a], "the collider did not move to its new cell");
        g.query_circle_into(DVec2::new(1.0, 1.0), 5.0, 0, &mut scratch);
        assert!(scratch.hits.is_empty(), "the collider is still in its old cell");

        // A sub-cell nudge keeps the same span and must still be found.
        assert!(g.update(a, DVec2::new(101.0, 101.0), 1.0));
        g.query_circle_into(DVec2::new(101.0, 101.0), 5.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![a]);
    }

    /// Repeated same-cell updates must not grow the bucket.
    ///
    /// The span-equality check in `update` skips the unhook/hook pair when
    /// membership cannot have changed. That skip is a performance property
    /// and is measured, not asserted — but a *broken* version that hooked
    /// without unhooking would push a duplicate index every call, which is
    /// observable: the collider would be yielded more than once, or the
    /// bucket would grow without bound. Both are caught here.
    #[test]
    fn repeated_same_cell_updates_do_not_duplicate_bucket_entries() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(1.0, 1.0), 1.0);
        let mut scratch = AoiScratch::new();

        for i in 0..64 {
            // Stays inside the same cell, so the span never changes.
            let nudge = 1.0 + (i as f64) * 0.01;
            assert!(g.update(a, DVec2::new(nudge, nudge), 1.0));
        }

        g.query_circle_into(DVec2::new(1.5, 1.5), 5.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![a], "64 same-cell updates must leave exactly one entry");

        // Crossing out and back must also leave the grid in a clean state.
        assert!(g.update(a, DVec2::new(500.0, 500.0), 1.0));
        assert!(g.update(a, DVec2::new(1.0, 1.0), 1.0));
        g.query_circle_into(DVec2::new(1.0, 1.0), 5.0, 0, &mut scratch);
        assert_eq!(scratch.hits, vec![a], "a round trip must not leave a duplicate");
        g.query_circle_into(DVec2::new(500.0, 500.0), 5.0, 0, &mut scratch);
        assert!(scratch.hits.is_empty(), "a round trip must not leave a stale entry");
    }

    /// `update` on a hole is a no-op, not a panic and not a resurrection.
    #[test]
    fn update_and_remove_reject_holes() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::ZERO, 1.0);
        assert!(g.remove(a));

        assert!(!g.remove(a), "removing twice must report nothing was there");
        assert!(!g.update(a, DVec2::new(5.0, 5.0), 1.0), "a hole must not be updatable");
        assert!(!g.slot_alive(a));
        assert!(!g.update(999, DVec2::ZERO, 1.0), "an out-of-range slot must not panic");
        assert!(!g.remove(999));
    }

    /// `len` counts colliders; `slot_count` counts the index space. They
    /// diverge exactly when holes exist, and anything sized per-slot (the
    /// AoI stamp vector) needs the latter.
    #[test]
    fn len_counts_colliders_slot_count_counts_slots() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(0.0, 0.0), 1.0);
        let _b = g.insert(DVec2::new(40.0, 0.0), 1.0);
        assert_eq!((g.len(), g.slot_count()), (2, 2));

        g.remove(a);
        assert_eq!((g.len(), g.slot_count()), (1, 2), "a hole keeps its slot");
        assert!(!g.is_empty());

        // Reuse fills the hole rather than growing the index space.
        g.insert(DVec2::new(80.0, 0.0), 1.0);
        assert_eq!((g.len(), g.slot_count()), (2, 2));
    }

    /// `clear` is the per-tick rebuild primitive: slot numbering restarts
    /// from zero so index-per-tick callers are unaffected, but handles from
    /// before the clear must not resolve against the new occupants.
    #[test]
    fn clear_restarts_slots_but_not_generations() {
        let mut g = SpatialGrid::new(10.0);
        let old = g.insert_tracked(DVec2::new(1.0, 1.0), 1.0, 0);
        assert_eq!(old.index, 0);

        g.clear();
        assert_eq!((g.len(), g.slot_count()), (0, 0));
        assert_eq!(g.resolve(old), None, "a handle must not survive a clear");

        let new = g.insert_tracked(DVec2::new(1.0, 1.0), 1.0, 0);
        assert_eq!(new.index, 0, "slot numbering restarts, as a fresh grid would");
        assert_ne!(new.generation, old.generation, "but the generation must not repeat");
        assert_eq!(g.resolve(old), None, "the pre-clear handle must still fail");
        assert_eq!(g.resolve(new), Some(0));
    }

    /// A cleared grid must behave exactly like a fresh one for the callers
    /// that rebuild every tick — same pairs, same query results.
    #[test]
    fn clear_leaves_a_grid_equivalent_to_a_fresh_one() {
        let build = |g: &mut SpatialGrid| {
            for i in 0..32u32 {
                let f = i as f64;
                g.insert(DVec2::new(f * 3.0, (f * 7.0) % 40.0), 6.0);
            }
        };

        let mut fresh = SpatialGrid::new(10.0);
        build(&mut fresh);

        let mut reused = SpatialGrid::new(10.0);
        build(&mut reused);
        reused.clear();
        build(&mut reused);

        assert_eq!(reused.len(), fresh.len());
        assert_eq!(reused.slot_count(), fresh.slot_count());
        assert_eq!(reused.query_pairs(), fresh.query_pairs(), "a cleared grid must requery identically");
    }

    /// Partition tags have to follow a slot through reuse, or a recycled
    /// slot leaks into the partition its previous occupant belonged to.
    #[test]
    fn a_reused_slot_takes_its_new_partition() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert_partitioned(DVec2::ZERO, 1.0, 7);
        g.remove(a);
        let b = g.insert_partitioned(DVec2::ZERO, 1.0, 9);
        assert_eq!(a, b, "expected slot reuse for this test to mean anything");

        let mut scratch = AoiScratch::new();
        g.query_circle_into(DVec2::ZERO, 5.0, 7, &mut scratch);
        assert!(scratch.hits.is_empty(), "the slot is still in its old partition");
        g.query_circle_into(DVec2::ZERO, 5.0, 9, &mut scratch);
        assert_eq!(scratch.hits, vec![b], "the slot did not join its new partition");
    }
}
