//! Broad-phase spatial grid + narrow-phase SAT primitives for 2D
//! collision.
//!
//! The grid ([`SpatialGrid`]) buckets colliders into fixed-size cells
//! and yields the set of possibly-overlapping index pairs. The SAT
//! helpers ([`circle_vs_circle`], [`obb_vs_obb`], [`circle_vs_obb`],
//! [`obb_axes`]) return `Some((normal, overlap))` when two shapes
//! penetrate.
//!
//! Everything here is index-based and game-agnostic: callers build a
//! flat `Vec<Collider>` of their own, insert into the grid, iterate
//! the returned pair list, and dispatch the correct SAT branch based
//! on their own shape flags. Filter logic (ship-vs-chunk pass-through,
//! per-pad occupancy, docked-lock, etc.) stays in the caller — the
//! engine gives you the pair list, not the resolution.

use glam::DVec2;
use std::collections::{HashMap, HashSet};

/// Cell-bucketed broad-phase.
///
/// Colliders are inserted with `(index, pos, radius)` — the grid puts
/// each collider into every cell its bounding square overlaps, so a
/// pair query only needs to read a single cell rather than a 3×3
/// neighbourhood. `query_pairs` returns unique index pairs (`a < b`).
pub struct SpatialGrid {
    cell_size: f64,
    /// Keyed by `(partition, cx, cy)`. The partition is an opaque
    /// caller-supplied tag (0 when unused) that hard-separates
    /// colliders which share coordinates but must never interact.
    ///
    /// Without it, a caller whose world stacks independent groups at
    /// the same coordinates gets every cross-group pair generated by
    /// the broad phase and then has to reject them one at a time —
    /// which is O(N^2) in the number of co-located groups no matter
    /// how cheap the rejection is. Partitioning keeps them out of the
    /// same bucket in the first place.
    cells:     HashMap<(u32, i32, i32), Vec<u32>>,
    /// Retained per-collider bounds so `query_pairs` doesn't need the
    /// caller to hand them back — one insert, one query.
    bounds:    Vec<(DVec2, f64)>,
    /// Partition tag per collider, parallel to `bounds`.
    parts:     Vec<u32>,
}

impl SpatialGrid {
    /// Build an empty grid with the given cell size (world units).
    /// Picking this well is a workload trade-off: much larger than a
    /// typical collider and each cell buckets many colliders, blowing
    /// up the per-pair scan under crowding; much smaller and each
    /// collider inserts into many cells. Ship-sized colliders top out
    /// around 50 m; 400 m is the shipping default in void_sim.
    pub fn new(cell_size: f64) -> Self {
        Self { cell_size, cells: HashMap::new(), bounds: Vec::new(), parts: Vec::new() }
    }

    /// Insert a collider with its centre + bounding radius. Returns
    /// the index the pair query will yield.
    ///
    /// Equivalent to `insert_partitioned(pos, rad, 0)` — use that when
    /// the world stacks independent groups at shared coordinates.
    pub fn insert(&mut self, pos: DVec2, rad: f64) -> u32 {
        self.insert_partitioned(pos, rad, 0)
    }

    /// Insert into a specific partition. Colliders in different
    /// partitions never share a cell and therefore never appear as a
    /// pair, however close together they are.
    pub fn insert_partitioned(&mut self, pos: DVec2, rad: f64, partition: u32) -> u32 {
        let idx = self.bounds.len() as u32;
        self.bounds.push((pos, rad));
        self.parts.push(partition);
        let (cx0, cy0) = self.cell(pos - DVec2::splat(rad));
        let (cx1, cy1) = self.cell(pos + DVec2::splat(rad));
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                self.cells.entry((partition, cx, cy)).or_default().push(idx);
            }
        }
        idx
    }

    /// Number of colliders inserted.
    pub fn len(&self) -> usize { self.bounds.len() }
    pub fn is_empty(&self) -> bool { self.bounds.is_empty() }

    /// Enumerate every unique index pair (`a < b`) whose bounding
    /// squares share at least one cell. Deduplicated via a packed-u64
    /// hash set so multi-cell colliders don't yield the same pair
    /// twice. Pair order within the result is unspecified.
    pub fn query_pairs(&self) -> Vec<(u32, u32)> {
        let mut checked: HashSet<u64> = HashSet::new();
        let pack = |a: u32, b: u32| -> u64 { ((a as u64) << 32) | b as u64 };
        let mut pairs: Vec<(u32, u32)> = Vec::new();
        for (i, &(pos, rad)) in self.bounds.iter().enumerate() {
            let part = self.parts[i];
            let (cx0, cy0) = self.cell(pos - DVec2::splat(rad));
            let (cx1, cy1) = self.cell(pos + DVec2::splat(rad));
            for cy in cy0..=cy1 {
                for cx in cx0..=cx1 {
                    let Some(bucket) = self.cells.get(&(part, cx, cy)) else { continue };
                    for &j in bucket {
                        if i as u32 == j { continue; }
                        let (a, b) = if (i as u32) < j { (i as u32, j) } else { (j, i as u32) };
                        if checked.insert(pack(a, b)) { pairs.push((a, b)); }
                    }
                }
            }
        }
        pairs
    }

    /// Enumerate indices whose bounding-square shares any cell the
    /// segment `a → b` passes through. Each index is yielded at most
    /// once. Cell traversal is a grid-DDA (Amanatides-Woo style) so a
    /// long segment only touches the cells it actually crosses, not the
    /// AABB of its endpoints — the latter degrades to O(dx·dy) for
    /// diagonal shots. Callers still need to run their own narrow-phase
    /// (e.g. `swept_hit`) against the returned candidates.
    ///
    /// The `+1` cell of pad on each side of the traversal mirrors the
    /// hand-rolled projectile grid the sim used to carry: it catches
    /// colliders straddling a cell boundary that the segment doesn't
    /// technically enter, but whose bounding square does.
    pub fn query_segment(&self, a: DVec2, b: DVec2) -> Vec<u32> {
        self.query_segment_in(a, b, 0)
    }

    /// `query_segment` restricted to one partition.
    pub fn query_segment_in(&self, a: DVec2, b: DVec2, partition: u32) -> Vec<u32> {
        let mut seen: HashSet<u32> = HashSet::new();
        let mut out:  Vec<u32>     = Vec::new();
        let visit_cell = |cx: i32, cy: i32,
                          seen: &mut HashSet<u32>,
                          out:  &mut Vec<u32>| {
            for pad_y in -1..=1 {
                for pad_x in -1..=1 {
                    let Some(bucket) = self.cells.get(&(partition, cx + pad_x, cy + pad_y))
                    else { continue };
                    for &idx in bucket {
                        if seen.insert(idx) { out.push(idx); }
                    }
                }
            }
        };

        // Grid-DDA from `a` to `b`. Fast-path a stationary segment.
        let (ax, ay) = self.cell(a);
        let (bx, by) = self.cell(b);
        if ax == bx && ay == by {
            visit_cell(ax, ay, &mut seen, &mut out);
            return out;
        }

        let dir = b - a;
        // Steps of ±1 in whichever axes actually change.
        let step_x = if dir.x > 0.0 { 1 } else if dir.x < 0.0 { -1 } else { 0 };
        let step_y = if dir.y > 0.0 { 1 } else if dir.y < 0.0 { -1 } else { 0 };
        // Parametric `t` at which the ray crosses the next cell boundary
        // in each axis. `t_delta` is how much `t` advances per full cell.
        let next_bound = |v: f64, step: i32| -> f64 {
            let cell_f = (v / self.cell_size).floor();
            if step > 0 { (cell_f + 1.0) * self.cell_size }
            else if step < 0 { cell_f * self.cell_size }
            else { f64::INFINITY }
        };
        let mut t_max_x = if step_x != 0 { (next_bound(a.x, step_x) - a.x) / dir.x } else { f64::INFINITY };
        let mut t_max_y = if step_y != 0 { (next_bound(a.y, step_y) - a.y) / dir.y } else { f64::INFINITY };
        let t_delta_x = if step_x != 0 { (self.cell_size / dir.x).abs() } else { f64::INFINITY };
        let t_delta_y = if step_y != 0 { (self.cell_size / dir.y).abs() } else { f64::INFINITY };

        let (mut cx, mut cy) = (ax, ay);
        visit_cell(cx, cy, &mut seen, &mut out);
        // Cap the step count as a safety net — a well-formed segment
        // needs at most |dx| + |dy| + 1 cells. `+ 4` to absorb the pad.
        let max_steps = (bx - ax).unsigned_abs() as usize
                      + (by - ay).unsigned_abs() as usize + 4;
        for _ in 0..max_steps {
            if cx == bx && cy == by { break; }
            if t_max_x < t_max_y {
                cx += step_x;
                t_max_x += t_delta_x;
            } else {
                cy += step_y;
                t_max_y += t_delta_y;
            }
            visit_cell(cx, cy, &mut seen, &mut out);
        }
        out
    }

    /// Enumerate indices whose bounding-square shares any cell the disc
    /// `center` / `radius` overlaps. Each index is yielded at most once.
    ///
    /// **Broad-phase only**, matching [`query_segment`](Self::query_segment):
    /// the result is every candidate in the cells covering the disc's AABB,
    /// not a distance-filtered set. Corner cells reach `radius * √2` past
    /// the centre and a cell holds anything anywhere inside it, so callers
    /// that need a true radius must run their own
    /// `(pos - center).length_squared() <= radius * radius` narrow-phase.
    /// Handing back the raw cell contents keeps the one caller that wants
    /// a cheap "roughly nearby" window from paying for a filter it would
    /// only redo with its own metric.
    pub fn query_circle(&self, center: DVec2, radius: f64) -> Vec<u32> {
        self.query_circle_in(center, radius, 0)
    }

    /// `query_circle` restricted to one partition.
    pub fn query_circle_in(&self, center: DVec2, radius: f64, partition: u32) -> Vec<u32> {
        let mut seen: HashSet<u32> = HashSet::new();
        let mut out:  Vec<u32>     = Vec::new();
        let (cx0, cy0) = self.cell(center - DVec2::splat(radius));
        let (cx1, cy1) = self.cell(center + DVec2::splat(radius));
        for cy in cy0..=cy1 {
            for cx in cx0..=cx1 {
                let Some(bucket) = self.cells.get(&(partition, cx, cy)) else { continue };
                for &idx in bucket {
                    if seen.insert(idx) { out.push(idx); }
                }
            }
        }
        out
    }

    #[inline]
    fn cell(&self, pos: DVec2) -> (i32, i32) {
        ((pos.x / self.cell_size).floor() as i32,
         (pos.y / self.cell_size).floor() as i32)
    }
}

// ── narrow-phase SAT ─────────────────────────────────────────────────

/// Swept segment `p0 → p1` vs a static circle at `center` / `radius`,
/// returning the **near-hit parameter** `t ∈ [0, 1]` — the fraction along
/// the segment at which it first touches the disc, so the contact point is
/// `p0 + (p1 - p0) * t`.
///
/// `Some(0.0)` means `p0` is already inside the disc (no entry crossing to
/// find). `None` means the segment misses entirely, or the disc lies
/// wholly behind `p0` / beyond `p1`.
///
/// Callers wanting only a yes/no should use [`segment_vs_circle`], which
/// is this function's `.is_some()`.
pub fn segment_vs_circle_t(p0: DVec2, p1: DVec2, center: DVec2, radius: f64) -> Option<f64> {
    let d = p1 - p0;
    let f = p0 - center;
    let a = d.dot(d);

    // Degenerate: stationary segment collapses to a point-in-disc test.
    if a == 0.0 {
        return if f.length() < radius { Some(0.0) } else { None };
    }

    let b = 2.0 * f.dot(d);
    let c = f.dot(f) - radius * radius;
    let disc = b * b - 4.0 * a * c;

    if disc < 0.0 { return None; }

    let sq = disc.sqrt();
    let t1 = (-b - sq) / (2.0 * a);
    let t2 = (-b + sq) / (2.0 * a);

    // Solution range [t1, t2] must overlap the segment [0, 1].
    if t1 > 1.0 || t2 < 0.0 { return None; }

    // Clamp the entry root into the segment: a start already inside the
    // disc has t1 < 0, and its first "contact" is t = 0.
    Some(t1.max(0.0))
}

/// Swept segment `p0 → p1` vs a static circle at `center` / `radius`.
/// `true` iff the segment (or its degenerate stationary point) intersects
/// the disc. Natural narrow-phase pair for [`SpatialGrid::query_segment`]:
/// query yields candidates, this checks each one.
///
/// Thin wrapper over [`segment_vs_circle_t`] for callers that don't need
/// the contact parameter.
#[inline]
pub fn segment_vs_circle(p0: DVec2, p1: DVec2, center: DVec2, radius: f64) -> bool {
    segment_vs_circle_t(p0, p1, center, radius).is_some()
}

/// Local axes of an OBB with rotation `rot` (rad). `[0]` is the box's
/// local +X in world space, `[1]` its local +Y.
#[inline]
pub fn obb_axes(rot: f64) -> [DVec2; 2] {
    let (s, c) = rot.sin_cos();
    [DVec2::new(c, s), DVec2::new(-s, c)]
}

/// Circle-vs-circle overlap probe. Returns `(normal, overlap)` where
/// `normal` points from B toward A (i.e. push A along `+normal`).
/// `None` when separated or coincident (< 0.001 m apart — degenerate
/// direction).
pub fn circle_vs_circle(
    pos_a: DVec2, rad_a: f64,
    pos_b: DVec2, rad_b: f64,
) -> Option<(DVec2, f64)> {
    let diff = pos_a - pos_b;
    let dist = diff.length();
    let min_dist = rad_a + rad_b;
    if dist >= min_dist || dist < 0.001 { return None; }
    Some((diff / dist, min_dist - dist))
}

/// OBB-vs-OBB overlap via SAT. Projects both boxes onto each of the 4
/// candidate axes (both boxes' local X and Y), takes the axis of MIN
/// penetration as the separating normal. Reduces to AABB when both
/// rotations are 0. Normal points from B toward A.
pub fn obb_vs_obb(
    pos_a: DVec2, half_a: [f64; 2], rot_a: f64,
    pos_b: DVec2, half_b: [f64; 2], rot_b: f64,
) -> Option<(DVec2, f64)> {
    let axes_a = obb_axes(rot_a);
    let axes_b = obb_axes(rot_b);
    let d = pos_a - pos_b;
    let axes = [axes_a[0], axes_a[1], axes_b[0], axes_b[1]];
    let mut min_overlap = f64::INFINITY;
    let mut best_axis = DVec2::new(1.0, 0.0);
    for axis in axes.iter() {
        let proj_a = half_a[0] * (axis.dot(axes_a[0])).abs()
                   + half_a[1] * (axis.dot(axes_a[1])).abs();
        let proj_b = half_b[0] * (axis.dot(axes_b[0])).abs()
                   + half_b[1] * (axis.dot(axes_b[1])).abs();
        let dist = d.dot(*axis).abs();
        let ov = (proj_a + proj_b) - dist;
        if ov <= 0.0 { return None; }
        if ov < min_overlap {
            min_overlap = ov;
            let sign = if d.dot(*axis) < 0.0 { -1.0 } else { 1.0 };
            best_axis = *axis * sign;
        }
    }
    Some((best_axis, min_overlap))
}

/// Circle-vs-OBB overlap via clamp-to-half-extents. Transforms the
/// circle centre into the box's local frame, clamps to `box_half`,
/// then either uses the offset from clamped-to-circle for a normal or
/// (when the circle centre sits INSIDE the box) picks the shallowest
/// local axis. Returned `normal` points from box toward circle by
/// default; pass `circle_is_a = false` to invert (matches the
/// caller-side "normal points from B toward A" convention regardless
/// of which side is the circle).
pub fn circle_vs_obb(
    circle_pos: DVec2, circle_r: f64,
    box_pos:    DVec2, box_half:  [f64; 2], box_rot: f64,
    circle_is_a: bool,
) -> Option<(DVec2, f64)> {
    let d = circle_pos - box_pos;
    let (s, c) = box_rot.sin_cos();
    let local = DVec2::new( c * d.x + s * d.y,
                           -s * d.x + c * d.y);
    let closest_local = DVec2::new(
        local.x.clamp(-box_half[0], box_half[0]),
        local.y.clamp(-box_half[1], box_half[1]),
    );
    let dv_local = local - closest_local;
    let dist = dv_local.length();
    if dist >= circle_r {
        return None;
    }
    if dist < 0.001 {
        // Circle centre sits inside box — push along the shallowest
        // local axis, then rotate back to world.
        let dx_out = box_half[0] - local.x.abs();
        let dy_out = box_half[1] - local.y.abs();
        let n_local = if dx_out < dy_out {
            DVec2::new(local.x.signum(), 0.0)
        } else {
            DVec2::new(0.0, local.y.signum())
        };
        let n_world = DVec2::new(c * n_local.x - s * n_local.y,
                                 s * n_local.x + c * n_local.y);
        let n_world = if circle_is_a { n_world } else { -n_world };
        Some((n_world, circle_r + dx_out.min(dy_out)))
    } else {
        let n_local = dv_local / dist;
        let n_world = DVec2::new(c * n_local.x - s * n_local.y,
                                 s * n_local.x + c * n_local.y);
        let n_world = if circle_is_a { n_world } else { -n_world };
        Some((n_world, circle_r - dist))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grid_yields_overlap_pair() {
        let mut g = SpatialGrid::new(10.0);
        g.insert(DVec2::new(0.0, 0.0), 2.0);
        g.insert(DVec2::new(1.0, 0.0), 2.0);
        g.insert(DVec2::new(1000.0, 0.0), 2.0);
        let pairs = g.query_pairs();
        assert!(pairs.contains(&(0, 1)));
        assert!(!pairs.iter().any(|&(a, b)| a == 2 || b == 2));
    }

    #[test]
    fn grid_pair_dedup() {
        // Two large colliders that straddle the same 4 cells; the pair
        // must appear exactly once in the query result.
        let mut g = SpatialGrid::new(10.0);
        g.insert(DVec2::new(0.0, 0.0), 15.0);
        g.insert(DVec2::new(5.0, 5.0), 15.0);
        let pairs = g.query_pairs();
        let count = pairs.iter().filter(|&&p| p == (0, 1)).count();
        assert_eq!(count, 1, "{pairs:?}");
    }

    #[test]
    fn circle_pair_overlap() {
        let (n, ov) = circle_vs_circle(
            DVec2::new(5.0, 0.0), 3.0,
            DVec2::new(0.0, 0.0), 3.0,
        ).expect("overlap");
        assert!((ov - 1.0).abs() < 1e-9);
        assert!((n - DVec2::new(1.0, 0.0)).length() < 1e-9);
    }

    #[test]
    fn circle_pair_separated() {
        assert!(circle_vs_circle(
            DVec2::new(10.0, 0.0), 1.0,
            DVec2::new(0.0, 0.0), 1.0,
        ).is_none());
    }

    #[test]
    fn axis_aligned_boxes_overlap() {
        let (_n, ov) = obb_vs_obb(
            DVec2::new(0.0, 0.0), [2.0, 2.0], 0.0,
            DVec2::new(3.0, 0.0), [2.0, 2.0], 0.0,
        ).expect("overlap");
        assert!((ov - 1.0).abs() < 1e-6);
    }

    #[test]
    fn separated_boxes_no_overlap() {
        assert!(obb_vs_obb(
            DVec2::new(0.0, 0.0), [1.0, 1.0], 0.0,
            DVec2::new(10.0, 0.0), [1.0, 1.0], 0.0,
        ).is_none());
    }

    #[test]
    fn segment_vs_circle_hits_and_misses() {
        assert!(segment_vs_circle(
            DVec2::new(-5.0, 0.0), DVec2::new(5.0, 0.0),
            DVec2::new(0.0, 0.0), 1.0,
        ));
        assert!(!segment_vs_circle(
            DVec2::new(-5.0, 10.0), DVec2::new(5.0, 10.0),
            DVec2::new(0.0, 0.0), 1.0,
        ));
        // Stationary segment inside the disc.
        assert!(segment_vs_circle(
            DVec2::new(0.5, 0.0), DVec2::new(0.5, 0.0),
            DVec2::new(0.0, 0.0), 1.0,
        ));
    }

    #[test]
    fn segment_vs_circle_t_reports_near_hit() {
        // Unit disc at origin, segment from x=-5 to x=+5 (length 10): the
        // entry crossing is at x = -1, i.e. 4/10 along.
        let t = segment_vs_circle_t(
            DVec2::new(-5.0, 0.0), DVec2::new(5.0, 0.0),
            DVec2::new(0.0, 0.0), 1.0,
        ).expect("segment crosses the disc");
        assert!((t - 0.4).abs() < 1e-9, "t = {t}");

        // Start already inside → first contact is t = 0, not a back-solve.
        let t = segment_vs_circle_t(
            DVec2::new(0.5, 0.0), DVec2::new(5.0, 0.0),
            DVec2::new(0.0, 0.0), 1.0,
        ).expect("start is inside the disc");
        assert_eq!(t, 0.0);

        // Disc entirely beyond the segment end → no hit.
        assert!(segment_vs_circle_t(
            DVec2::new(-5.0, 0.0), DVec2::new(-3.0, 0.0),
            DVec2::new(0.0, 0.0), 1.0,
        ).is_none());

        // Miss.
        assert!(segment_vs_circle_t(
            DVec2::new(-5.0, 10.0), DVec2::new(5.0, 10.0),
            DVec2::new(0.0, 0.0), 1.0,
        ).is_none());
    }

    #[test]
    fn circle_query_covers_cells_and_excludes_far_ones() {
        let mut g = SpatialGrid::new(100.0);
        let near = g.insert(DVec2::new(10.0, 10.0), 0.0);
        let adj  = g.insert(DVec2::new(150.0, 10.0), 0.0);   // next cell over
        let far  = g.insert(DVec2::new(9_000.0, 0.0), 0.0);  // way outside

        let hits = g.query_circle(DVec2::new(0.0, 0.0), 100.0);
        assert!(hits.contains(&near));
        assert!(hits.contains(&adj), "adjacent cell is inside the AABB");
        assert!(!hits.contains(&far));

        // Radius == cell size always yields the 3×3 window, whatever the
        // alignment of the query point within its cell.
        for px in [0.0, 50.0, 99.9, 100.0] {
            let mut probe = SpatialGrid::new(100.0);
            for cy in -2..=2 {
                for cx in -2..=2 {
                    probe.insert(DVec2::new(cx as f64 * 100.0 + 50.0,
                                            cy as f64 * 100.0 + 50.0), 0.0);
                }
            }
            let n = probe.query_circle(DVec2::new(px, 50.0), 100.0).len();
            assert_eq!(n, 9, "px = {px} should hit a 3x3 window");
        }
    }

    #[test]
    fn segment_query_hits_traversed_cells() {
        // Grid-DDA against a diagonal shot: the segment must yield both
        // colliders on its path but skip a far-off one.
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(5.0, 5.0),   1.0);   // start cell
        let b = g.insert(DVec2::new(35.0, 35.0), 1.0);   // end cell
        let c = g.insert(DVec2::new(15.0, 15.0), 1.0);   // en-route
        let d = g.insert(DVec2::new(500.0, 0.0), 1.0);   // far away
        let hits = g.query_segment(DVec2::new(0.0, 0.0), DVec2::new(40.0, 40.0));
        assert!(hits.contains(&a));
        assert!(hits.contains(&b));
        assert!(hits.contains(&c));
        assert!(!hits.contains(&d));
    }

    #[test]
    fn segment_query_stationary_returns_local_bucket() {
        let mut g = SpatialGrid::new(10.0);
        let a = g.insert(DVec2::new(5.0, 5.0), 1.0);
        let far = g.insert(DVec2::new(100.0, 100.0), 1.0);
        let hits = g.query_segment(DVec2::new(5.0, 5.0), DVec2::new(5.0, 5.0));
        assert!(hits.contains(&a));
        assert!(!hits.contains(&far));
    }

    #[test]
    fn segment_query_dedups() {
        // Wide collider spanning several cells must appear once.
        let mut g = SpatialGrid::new(10.0);
        let big = g.insert(DVec2::new(20.0, 20.0), 15.0);
        let hits = g.query_segment(DVec2::new(0.0, 0.0), DVec2::new(40.0, 40.0));
        assert_eq!(hits.iter().filter(|&&i| i == big).count(), 1);
    }

    #[test]
    fn circle_vs_box_edge_penetration() {
        let (n, ov) = circle_vs_obb(
            DVec2::new(3.0, 0.0), 2.0,
            DVec2::new(0.0, 0.0), [2.0, 2.0], 0.0,
            true,
        ).expect("overlap");
        assert!((ov - 1.0).abs() < 1e-6);
        assert!(n.x > 0.0, "normal should push circle further from box");
    }
}

#[cfg(test)]
mod partition_tests {
    use super::*;

    /// Colliders in different partitions never pair, however close.
    #[test]
    fn different_partitions_never_pair() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert_partitioned(DVec2::ZERO, 50.0, 1);
        let b = g.insert_partitioned(DVec2::ZERO, 50.0, 2);
        let pairs = g.query_pairs();
        assert!(!pairs.contains(&(a.min(b), a.max(b))),
            "colliders in different partitions must not pair");
        assert!(pairs.is_empty());
    }

    #[test]
    fn same_partition_still_pairs() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert_partitioned(DVec2::ZERO, 50.0, 7);
        let b = g.insert_partitioned(DVec2::new(10.0, 0.0), 50.0, 7);
        assert_eq!(g.query_pairs(), vec![(a.min(b), a.max(b))]);
    }

    /// The un-partitioned API is partition 0, so existing callers are
    /// unaffected.
    #[test]
    fn plain_insert_behaves_as_partition_zero() {
        let mut g = SpatialGrid::new(400.0);
        let a = g.insert(DVec2::ZERO, 50.0);
        let b = g.insert_partitioned(DVec2::new(10.0, 0.0), 50.0, 0);
        assert_eq!(g.query_pairs(), vec![(a.min(b), a.max(b))]);
    }

    /// **The scaling property this exists for.** N groups stacked at one
    /// coordinate must stay linear, not quadratic. Un-partitioned, N
    /// co-located colliders generate N*(N-1)/2 pairs; partitioned, zero.
    #[test]
    fn stacked_groups_do_not_explode_the_pair_count() {
        const GROUPS: u32 = 200;
        let mut partitioned = SpatialGrid::new(400.0);
        let mut flat        = SpatialGrid::new(400.0);
        for g in 0..GROUPS {
            partitioned.insert_partitioned(DVec2::ZERO, 50.0, g);
            flat.insert(DVec2::ZERO, 50.0);
        }
        assert_eq!(partitioned.query_pairs().len(), 0,
            "distinct partitions must yield no cross pairs");
        assert_eq!(flat.query_pairs().len() as u32, GROUPS * (GROUPS - 1) / 2,
            "sanity: un-partitioned really is quadratic here");
    }

    #[test]
    fn circle_and_segment_queries_respect_partitions() {
        let mut g = SpatialGrid::new(400.0);
        let mine   = g.insert_partitioned(DVec2::ZERO, 50.0, 3);
        let _other = g.insert_partitioned(DVec2::ZERO, 50.0, 4);

        assert_eq!(g.query_circle_in(DVec2::ZERO, 100.0, 3), vec![mine]);
        assert_eq!(g.query_segment_in(DVec2::new(-500.0, 0.0), DVec2::new(500.0, 0.0), 3),
                   vec![mine]);
    }
}
